### PR TITLE
Download default templates if it does not exists before applying

### PR DESCRIPTION
**Pull request by asbubam**
* Download default templates to {USER HOME}/.klocust if it does not exists before applying.
* If user download klocust files from co-worker first. He|She doesn't have default templates in {USER_HOME}/.klocust/_default_templates. 
   So download default templates if it does not exist before applying too.

### CODE REVIEW

**Comment by GwonsooLee** [comment]
What if someone changes template contents before?

**Comment by asbubam** [comment]
> What if someone changes template contents before?

Basically the premise of klocust that **{USER_HOME}/.klocust/default_templates** is not change.
Because It's default yaml file templates. And it's possible that user can customize and share it to co-workers too.

I think we can divide it to **klocust default** and **user default** with next version in future.

**Comment by GwonsooLee** [comment]
If it is not changed, then I think there is no need to make template itself. 
The reason we use yaml file for template is that we can change values of something and manage them in the form of code. If name is the only variable and default template is not going to be changed, then I think we can make it without downloading template.

If users can change template and share what they change with code, then path (`{USER_HOME}/.klocust`) doesn't seem to be right. Like helm, we can download the code in specific directory(i.e. current directory or create new directory in current directory) so that they can share them with source management tools such as github.

**Comment by asbubam** [comment]
How about this?

find templates with next priorities.
priority 1)  klocust apply hello -templates=/PATH  : custom path
priority 2) ${PWD}/.klocust/_default_templates      : user can customize and share templates in same projects.
priority 3) $HOME/.klocust/default_templates.       : user don't need to any customize templates, just override values.

**Comment by GwonsooLee** [comment]
> How about this?
> 
> find templates with next priorities.
> priority 1) klocust apply hello -templates-path=/PATH : custom path
> priority 2) ${PWD}/.klocust/_default_templates : user can customize and share templates in same projects.
> priority 3) $HOME/.klocust/default_templates. : user don't need to any customize templates, just override values.

For priority2, why don't we use .(dot = current directory) like helm? Because `.klocust` in the middle of directory could be kind of restriction for users.
If users want to specify the path, then they can use priority1 method.

For Priority3, I suggest that we can skip download part at all because, as you mentioned, it is not going to be customized. If user wants to change and share, they can download templates to specific directory and use that directory with Priority 1 method. 

How about this?

**Comment by asbubam** [comment]
Case Priority 3
I thought If user just want to override values in {name}-klocust.yaml and doesn't need to any customize templates. Then, priority 1,2 will be annoying to that user.

Case Priority 1, 2 can be any format

**Comment by asbubam** [comment]
Hm, May be there is the better way for this. I'll think about it.

**Review by GwonsooLee — APPROVED** [review]
👍

**Comment by asbubam** [comment]
We had video chat review. And we've got next conclusion.

1. Don't create any files to local environment without klocust.yaml & locustfile.py files.
2. Template Versioning in klocust.yaml file. And If it can, it will be update next version of klocust binary.

So this PR will close.

**Pull request closed without merging**
